### ISSUE TITLE
allow changing return key from text

### ISSUE THREAD

**Issue by roozbehk** [n8nhackers/n8n-nodes-document-generator#1]
### Describe the function you would like to have

hello when I have multiple document generators, all of them return the value in text key. is it possible to allow custom keys.

**Comment by mcolomer** [comment]
Hi @roozbehk 

I have uploaded a new version where you can define the name of the output property (instead of the default name 'text').
Could you try it please?

Thank you!

**Comment by roozbehk** [comment]
Awsome! I can confirm I can see "Define a Custom Output Key" Option now and the feature works as expected! Thank you @mcolomer

**Comment by mcolomer** [comment]
Perfect.

Enjoy it!
