### ISSUE TITLE
Compatability newer n8n versions

### ISSUE THREAD

**Issue by HammieJT** [n8nhackers/n8n-nodes-document-generator#4]
### Describe the bug

Hello,

Ever since upgrading to (then) the newest version of N8N (0.217.1) after a few days the custom node stops working and it gives an error in the workflow.
![image](https://user-images.githubusercontent.com/18553664/226933171-82ea2275-25e1-41e2-87b6-26354f9ac9a9.png)

The only one to fix this is by uninstalling the node and reinstalling it. Then it works for a few days and after that the cycle repeats. 

The error n8n gives is:
Problem activating workflow
The following error occurred on workflow activation:
Node not found: n8n-nodes-document-generator.DocumentGenerator

Under settings:
![image](https://user-images.githubusercontent.com/18553664/226933481-a53ecc1a-0ec2-4805-95fc-e3181d9ccb80.png)

Perhaps I am doing something wrong or configured it incorrectly, but I would like to come up with a fix because it is a great custom node :)

### Describe the expected behavior

Not having to reinstall the plugin every few days

### What is your Node.js version?

i dont know

### What is your n8n version?

0.217.1

### What is your n8n-nodes-text-manipulation version?

1.0.3

### What operating system are you seeing the problem on?

Linux

### Operating system version (or if other, then please fill in complete name and version)

Docker

**Comment by mcolomer** [comment]
New version was added.
Could you check if 1.0.8 fixes your issues?
