### ISSUE TITLE
Integrating Handlebar helpers 

### ISSUE THREAD

**Issue by codes-onthe-side** [n8nhackers/n8n-nodes-document-generator#6]
### Describe the function you would like to have

Your community node is fantastic, the only thing that it's missing is helper functions.

@aprosvetova has created this in a fork using this handlebars repo (https://github.com/jaredwray/fumanchu) which combines handlebar-helpers & handlebars. You could potentially merge his fork into your and update the npm-registry for the whole n8n community to be able to use?

https://github.com/aprosvetova/n8n-nodes-document-generator

**Comment by mcolomer** [comment]
Hi @codes-onthe-side ,

Code was added to current community node.
Some extra improvements were made to documentation. 

Sample workflow is added to root folder.

Hope this helps.
